### PR TITLE
add a draft for the *NU*shell *P*ac*K*a*G*es Repository (*nupkgs*)

### PR DESCRIPTION
**Pull request by amtoine**
i was having a look at `awesome-nu` the other and thought i could give a go at drawing the list of all know *more or less* packages out there :yum: 

in this PR, until we have a proper repo for this, i introduce the **NU**shell **U**ser **R**epository (**NUUR**) as a `nuur.nuon` file in the root of `nupm`:
- "_package_"s are repositories already with a `package.nuon` inside them
- "_plugin_"s are plugin repositories, i.e. with a `Cargo.toml`
- i've also added "_script_"s and "_completion_"s from `awesome-nu` which might be of some interest later

> **Note**
> all the paths in this `nuur.nuon` file are URLs within which one can directly find metadata files such as `package.nuon` or `Cargo.toml`, i.e. these are the paths where the package truely *is*

### CODE REVIEW

**Comment by amtoine** [comment]
i've been able, by applying the following patch
```diff
diff --git a/nupm/install.nu b/nupm/install.nu
index d358d7d..1f7d487 100644
--- a/nupm/install.nu
+++ b/nupm/install.nu
@@ -138,4 +138,5 @@ export def main [
     }
 
     # TODO: pull down the files into the local `nupm` store
+    $files | to nuon
 }
```
to get the proper lists of files:
```bash
> nupm install https://github.com/amtoine/nu-git-manager | from nuon | select path sha
╭────┬──────────────────────────────┬──────────────────────────────────────────╮
│  # │             path             │                   sha                    │
├────┼──────────────────────────────┼──────────────────────────────────────────┤
│  0 │ LICENSE                      │ f288702d2fa16d3cdf0035b15a9fcbc552cd88e7 │
│  1 │ README.md                    │ 3515d608bf95e72ad352a92ceb428a0987ce545f │
│  2 │ mod.nu                       │ ac0b1bc6360ce700e96b3adb332d7bca0265c32c │
│  3 │ package.nuon                 │ 2bcfe8d8e6f3cc13eb9f49b2e0a6c21f4e8196c9 │
│  4 │ docs/README.md               │ 1ee395d15b0ccc225ed2ab3574236301056d84ef │
│  5 │ toolkit/mod.nu               │ 0075407d5e5662db2f87c345f1d992d669d56736 │
│  6 │ docs/installation/README.md  │ 0ef9248feac689be5c02eebd417e3f48270880e5 │
│  7 │ docs/installation/manual.md  │ 9a17f01543c0ea8b50dff522e87a75f5a8f0b6e6 │
│  8 │ docs/installation/nupm.md    │ 911607a1733290c763a1b5eceeafe418e0a6d985 │
│  9 │ src/gm/mod.nu                │ f9c79b532c4bfd7769fcfcfa23d179b6bee00965 │
│ 10 │ src/sugar/dotfiles.nu        │ 4652240da862cc177315118de35aca23af3d86af │
│ 11 │ src/sugar/gh.nu              │ eca8b178d835b13292083994f416566cd6088f21 │
│ 12 │ src/sugar/gist.nu            │ ccb727d7b393787fc4fb6b4f2de193971e56dc2e │
│ 13 │ src/sugar/git.nu             │ 44ea925db6d7389eab53ccef10adda0ebf75920a │
│ 14 │ src/sugar/mod.nu             │ 38662f45b94c1d67cb9c7885ee91b7f5f22b1583 │
│ 15 │ src/gm/utils/utils.nu        │ 70616d72f92664566e8cd2eec6d205b518f7c77b │
│ 16 │ src/sugar/completions/git.nu │ 7e7e459c4de10360b095329a1d2682606ec7f4b6 │
│ 17 │ src/sugar/completions/mod.nu │ e69de29bb2d1d6434b8b29ae775ad8c2e48c5391 │
╰────┴──────────────────────────────┴──────────────────────────────────────────╯
```
```bash
> nupm install https://github.com/amtoine/zellij-layouts --path nu-zellij | from nuon | select path sha
╭───┬────────────────────────┬──────────────────────────────────────────╮
│ # │          path          │                   sha                    │
├───┼────────────────────────┼──────────────────────────────────────────┤
│ 0 │ nu-zellij/LICENSE      │ f288702d2fa16d3cdf0035b15a9fcbc552cd88e7 │
│ 1 │ nu-zellij/README.md    │ 94d3f2ee6ccf29da8748c3368e78aa4fc5663b1b │
│ 2 │ nu-zellij/mod.nu       │ ee3f9bd929683b17dc4165dd40b65ab5ce299e4a │
│ 3 │ nu-zellij/package.nuon │ 0ec0854df3a3b8d66fc6a7b76ad7241f16cb9d84 │
╰───┴────────────────────────┴──────────────────────────────────────────╯
```

**Comment by amtoine** [comment]
> try saing `nuur.nuon` loud smile
>
:shushing_face: :laughing:
 
> I think that we should go with something pronounceable.
>
makes sense :eyes:  

> I see you've been inspired by Arch (AUR), how about Nix's nixpkgs inspired: `nupkgs`? Or simply `nu_packages` /`nupm_packages`?
>
do you mean `nupkgs` or `nupkgs.nuon` instead of `nuur.nuon`?
that looks easier to say :ok_hand:

**Comment by skelly37** [comment]
> do you mean `nupkgs` or `nupkgs.nuon` instead of `nuur.nuon`? that looks easier to say ok_hand
Yeah, `nupkgs` as a repo name, `nupkgs.nuon` as the actual repo cache/index

**Comment by amtoine** [comment]
renamed in cb8161c :yum:

**Comment by skelly37** [comment]
How about PR rename? 😋

**Review by skelly37 — APPROVED** [review]
Sorry, I thought I have already approved that 😅

**Pull request merged**
